// (C) Copyright 2006-2009 Hewlett-Packard Development Company, L.P.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//

// $Id: token_queue.h 11 2010-01-08 13:20:58Z paolofrb $
#ifndef CPU_TOKEN_QUEUE_H
#define CPU_TOKEN_QUEUE_H

enum QueueType { Linear, Circular };

#define TOKEN_QUEUE_CPU  0x0000000000000001
#define TOKEN_QUEUE_DISK 0x0000000000000002
#define TOKEN_QUEUE_NIC  0x0000000000000004

struct TokenQueue 
{
	void* unused1;
	uint64_t *first;
	uint64_t *last;
	uint64_t *head;
	uint64_t *tail;
	uint64_t devid;
	QueueType type;
	uint64_t flags;
	void     *anything;
};

#endif
